### ISSUE TITLE
[UI] Scan button 'spammable'

### ISSUE THREAD

**Issue by MonteOzdemir** [DriverCity/SPARK#16]
Both in driver app(paid parking view) and attendant app(disc and smart meter view) scan buttons are spammable for unlimited time. This makes application scan for bluetooth devices unlimited amount of times at the same time and displaying the results for each by refreshing view after each scan ends.
If there is no device detected this results in user getting spammed back with dialog box "Nothing detected .." while making application unusable.

**Comment by TanjaLeh** [comment]
Fixed for all scan button in attendant and driver app
